config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :user_projects, only: [:create, :update, :destroy]
  resources :user_groups, only: [:create, :update, :destroy]

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      confirmation: 'users/confirmations',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }, path: 'users', path_names: {
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'sign_up'
  }
  resources :users, only: [:index, :show]
  resources :tasks
  resources :projects
  resources :groups
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users,-> {where(user_groups: {accepted: true})}, through: :user_groups, source: :user
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :projects
end

app/models/group_task.rb
class GroupTask < ApplicationRecord
  belongs_to :task
  belongs_to :group
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: "User"
  belongs_to :notifiable, polymorphic: true
  after_commit -> {NotificationRelayJob.perform_later(self)}
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_tasks
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :tasks, through: :project_tasks
  has_many :completed_tasks, -> {where(tasks: {completed: true})}, through: :project_tasks, source: :task
  belongs_to :group
  before_destroy :destroy_user_projects

  def progress
    ((completed_tasks.count.to_f/tasks.count.to_f)*100)
  end

  def destroy_user_projects
    self.user_projects.delete_all
    self.tasks.delete_all
  end
end

app/models/project_task.rb
class ProjectTask < ApplicationRecord
  belongs_to :task
  belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_tasks
  has_many :tasks, through: :user_tasks
  has_many :user_projects
  has_many :projects, through: :user_projects
  has_many :user_groups
  has_many :owned_groups, class_name: "Group", foreign_key: "owner_id"
  has_many :recieved_group_invites, class_name: "UserGroup", foreign_key: "group_id"

  has_many :active_groups, -> {where(user_groups: {accepted: true})}, through: :user_groups, source: :group
  has_many :received_groups, -> {where(user_groups: {accepted: true})}, through: :recieved_group_invites, source: :user
  has_many :pending_groups, -> {where(user_groups: {accepted: false})}, through: :user_groups, source: :group
  has_many :requested_groups, -> {where(user_groups: {accepted: false})}, through: :recieved_group_invites, source: :user


  has_many :friendships
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"

  has_many :active_friends, -> {where(friendships: {accepted: true})}, through: :friendships, source: :friend
  has_many :received_friends, -> {where(friendships: {accepted: true})}, through: :received_friendships, source: :user
  has_many :pending_friends, -> {where(friendships: {accepted: false})}, through: :friendships, source: :friend
  has_many :requested_friends, -> {where(friendships: {accepted: false})}, through: :received_friendships, source: :user

  has_many :notifications, foreign_key: :recipient_id


  def full_name
    first_name + ' ' + last_name
  end

  def owner?(group)
    owned_groups.include?(group)
  end

  def friends
    active_friends | received_friends
  end

  def friends_pending
    pending_friends | requested_friends
  end

  def friends_with?(user)
    friends.include?(user)
  end

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end

  def groups
    active_groups | received_groups
  end

  def groups_pending
    pending_groups | requested_groups
  end

  def in_group?(group)
    groups.include?(group)
  end

  def remove_group(group)
    current_user.groups.destroy(group)
  end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @group = Group.find(params[:id])
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
    @users = User.all
  end

  def create
    @group = current_user.owned_groups.create(group_params)
    redirect_to users_path(current_user)
  end

  def update
  end

  def destroy
  end

  def group_params
    params.require(:group).permit(:title, :description, :owner_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def check_email
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def show
  end

  def new
    @task = Task.new
    @project = Project.new
  end

  def create
    params[:task][:completed] = false
    if params[:task][:project_id].nil?
      @task = current_user.tasks.create(task_params)
    else
      @project = Project.find(params[:task][:project_id])
      @task = @project.tasks.create(task_params)
    end
    respond_to do |format|
      format.html {redirect_to request.referrer}
      format.js
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    if params[:task][:project_id]
      @task = Project.find(params[:task][:project_id]).tasks.find(params[:id])
      @task.update(task_params)
    else
      @task = current_user.tasks.find(params[:id])
      @task.update(task_params)
    end
    respond_to do |format|
      format.html {redirect_to request.referrer}
      format.js
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    current_user.tasks.delete(@task)
    @task.destroy
  end

  def task_params
    params.require(:task).permit(:title, :description, :priority, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    resource.errors.full_messages.map { |msg| content_tag(:l, msg) }
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_active_group.html.erb
<li id="Group<%= active_group.id %>" class="collection-item"><%= link_to active_group.title, group_path(active_group) %>
  <%= link_to "Leave Group", user_group_path(id: active_group.id, user_id: current_user.id), class: "right", method: "delete", remote: true %></li>

app/views/groups/_group.html.erb
<li id="Group<%= group.id %>" class="collection-item"><%= link_to group.title, group_path(group) %>
  <% if current_user.owner?(group) %>
  <a href="<%= edit_group_path(group) %>" class="right"><i class="material-icons">mode_edit</i></a>
  <% end %>
</li>

app/views/groups/_pending_group.html.erb
<% if !current_user.owner?(pending_group) %>
    <li id="Group<%= pending_group.id %>" class="collection-item"><%= link_to pending_group.title, group_path(pending_group) %>
      <div class="right">
        <%= form_with model: current_user, url: user_group_path(pending_group), remote: true do |f| %>
            <%= f.submit 'Accept'.html_safe, class: "btn-flat" %>
        <% end %>
      </div>
      <div class="right">
        <%= form_with model: current_user, url: user_group_path(id: pending_group.id, user_id: current_user.id), method: :delete, remote: true do |f| %>
            <%= f.submit 'Decline', class: "btn-flat" %>
        <% end %>
      </div>
    </li>
<% end %>

app/views/groups/create.html.erb
<h1>Group#create</h1>
<p>Find me in app/views/group/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Group#destroy</h1>
<p>Find me in app/views/group/destroy.html.erb</p>

app/views/groups/edit.html.erb
<div class="row">
  <div class="col s12 m4">
    <div class="card">
      <div class="card-content">
        <div class="card-title"><%= @group.title %></div>
        <div class="card-block">
          <%= @group.description %>
          <% if current_user.owner?(@group) %>
              <%= form_with model: @group, method: :patch do |f| %>
                  <%= f.label :title %>
                  <%= f.text_field :title %>
                  <%= f.label :description %>
                  <%= f.text_area :description, class: "materialize-textarea" %>
                  <%= f.submit "Update Group", class: "btn" %>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col s12 m4">
    <h3 class="card-title">Projects</h3>
    <div class="card-block">
      <div class="card">
        <div class="card-content">
          <div class="card-title">All Projects</div>
          <div class="card-block">
            <ul class="collapsible" id="project-list">
                  <%= render @group.projects %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col s12 m4">
    <h3 class="card-title">Users</h3>
    <div class="card-block">
      <div class="card">
        <div class="card-content">
          <div class="card-block">
            <div class="card-title">Owner</div>
            <ul class="collection" id="group-project-list">
              <li id="User<%= @group.owner.id %>" class="collection-item"><%= @group.owner.username %></li>
            </ul>
            <div class="card-title">Members</div>
            <ul class="collection" id="user-list">
              <%= render @group.users %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="fixed-action-btn click-to-toggle">
  <a class="btn-floating btn-large red">
    <i class="material-icons">add</i>
  </a>
  <ul>
    <li>
      <a href="#add_user" class="btn-floating red tooltipped" data-position="left" data-tooltip="Add User"><i class="material-icons">perm_identity</i></a>
    </li>
    <li>
      <a href="#new_project" class="btn-floating red tooltipped" data-position="left" data-tooltip="Add Project"><i class="fa fa-tasks"></i></a>
    </li>
  </ul>
</div>
<%= form_with(model: @group.projects.new) do |f| %>
    <div class="modal bottom-sheet" id="new_project">
      <div class="modal-content">
        <%= f.hidden_field :group_id, value: @group.id %>
        <h4>Create Project</h4>
        <div class="input-field">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>
        <div class="input-field">
          <%= f.label :description %>
          <%= f.text_area :description, class: "materialize-textarea" %>
        </div>
        <div class="input-field">
          <%= f.submit 'Create Project', class: "btn" %>
        </div>
      </div>
    </div>
<% end %>
<div class="modal bottom-sheet" id="add_user">
  <div class="modal-content">
    <%= form_with(model: UserGroup.create, remote: true) do |f| %>
        <%= f.hidden_field :group_id, value: @group.id %>
        <div class="input-field">
          <%= f.select :users, @users.collect {|u| [u.username, u.id]}, {include_blank: false}, id: "add_users", multiple: true, style: "width: 100%" %>
        </div>
        <%= f.submit "Add Users", class: "btn" %>
    <% end %>
    <script>
        function formatExample(user) {
            var originalOption = $(user.element);
            return "   " + user.text;
        }

        $('select#add_users').select2({
            placeholder: "Add a User",
            allowClear: true,
            formatResult: formatExample,
            formatSelection: formatExample,
            escapeMarkup: function (m) {
                return m;
            }
        });
    </script>
  </div>
</div>
<script>
    $('.modal').modal({
            dismissible: true, // Modal can be dismissed by clicking outside of the modal
            opacity: .5, // Opacity of modal background
            inDuration: 300, // Transition in duration
            outDuration: 200, // Transition out duration
            startingTop: '4%', // Starting top style attribute
            endingTop: '10%' // Ending top style attribute
        }
    );
</script>

app/views/groups/index.html.erb
<div class="container">
  <div class="card">
    <div class="card-content">
      <div class="card-title"><%= @group.title %></div>
      <div class="card-block">
        <%= @group.description %>
      </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="card">
    <div class="card-content">
      <div class="card-title">Create Group</div>
      <%= form_with model: @group do |f| %>
          <%= f.hidden_field :owner_id, value: current_user.id %>
          <%= f.label :title %>
          <%= f.text_field :title %>
          <%= f.label :description %>
          <%= f.text_area :description, class: "materialize-textarea" %>
          <%= f.submit "Create Group", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="row">
  <div class="col s12 m4">
    <div class="card">
      <div class="card-content">
        <div class="card-title"><%= @group.title %></div>
        <div class="card-block">
          <%= @group.description %>
        </div>
      </div>
    </div>
  </div>
  <div class="col s12 m4">
    <h3 class="card-title">Projects</h3>
    <div class="card-block">
      <div class="card">
        <div class="card-content">
          <div class="card-title">All Projects</div>
          <div class="card-block">
            <ul class="collapsible" id="user-project-list">
                <%= render @group.projects %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col s12 m4">
    <h3 class="card-title">Users</h3>
    <div class="card-block">
      <div class="card">
        <div class="card-content">
          <div class="card-block">
            <div class="card-title">Owner</div>
            <ul class="collection" id="group-project-list">
              <li id="User<%= @group.owner.id %>" class="collection-item"><%= @group.owner.username %></li>
            </ul>
            <div class="card-title">Members</div>
            <ul class="collection" id="group-project-list">
              <% @group.users.each do |u| %>
                  <% if u != @group.owner %>
                      <li id="User<%= u.id %>" class="collection-item"><%= u.username %></li>
                  <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/update.html.erb
<h1>Group#update</h1>
<p>Find me in app/views/group/update.html.erb</p>