config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :user_projects, only: [:create, :update, :destroy]
  resources :user_groups, only: [:create, :update, :destroy]

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      confirmation: 'users/confirmations',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }, path: 'users', path_names: {
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'sign_up'
  }
  resources :users, only: [:index, :show]
  resources :tasks
  resources :projects
  resources :groups
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users,-> {where(user_groups: {accepted: true})}, through: :user_groups, source: :user
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :projects
end

app/models/group_task.rb
class GroupTask < ApplicationRecord
  belongs_to :task
  belongs_to :group
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: "User"
  belongs_to :notifiable, polymorphic: true
  after_commit -> {NotificationRelayJob.perform_later(self)}
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_tasks
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :tasks, through: :project_tasks
  has_many :completed_tasks, -> {where(tasks: {completed: true})}, through: :project_tasks, source: :task
  belongs_to :group
  before_destroy :destroy_user_projects

  def progress
    ((completed_tasks.count.to_f/tasks.count.to_f)*100)
  end

  def destroy_user_projects
    self.user_projects.delete_all
    self.tasks.delete_all
  end
end

app/models/project_task.rb
class ProjectTask < ApplicationRecord
  belongs_to :task
  belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_tasks
  has_many :tasks, through: :user_tasks
  has_many :user_projects
  has_many :projects, through: :user_projects
  has_many :user_groups
  has_many :owned_groups, class_name: "Group", foreign_key: "owner_id"
  has_many :recieved_group_invites, class_name: "UserGroup", foreign_key: "group_id"

  has_many :active_groups, -> {where(user_groups: {accepted: true})}, through: :user_groups, source: :group
  has_many :received_groups, -> {where(user_groups: {accepted: true})}, through: :recieved_group_invites, source: :user
  has_many :pending_groups, -> {where(user_groups: {accepted: false})}, through: :user_groups, source: :group
  has_many :requested_groups, -> {where(user_groups: {accepted: false})}, through: :recieved_group_invites, source: :user


  has_many :friendships
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"

  has_many :active_friends, -> {where(friendships: {accepted: true})}, through: :friendships, source: :friend
  has_many :received_friends, -> {where(friendships: {accepted: true})}, through: :received_friendships, source: :user
  has_many :pending_friends, -> {where(friendships: {accepted: false})}, through: :friendships, source: :friend
  has_many :requested_friends, -> {where(friendships: {accepted: false})}, through: :received_friendships, source: :user

  has_many :notifications, foreign_key: :recipient_id


  def full_name
    first_name + ' ' + last_name
  end

  def owner?(group)
    owned_groups.include?(group)
  end

  def friends
    active_friends | received_friends
  end

  def friends_pending
    pending_friends | requested_friends
  end

  def friends_with?(user)
    friends.include?(user)
  end

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end

  def groups
    active_groups | received_groups
  end

  def groups_pending
    pending_groups | requested_groups
  end

  def in_group?(group)
    groups.include?(group)
  end

  def remove_group(group)
    current_user.groups.destroy(group)
  end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def check_email
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def show
  end

  def new
    @task = Task.new
    @project = Project.new
  end

  def create
    params[:task][:completed] = false
    if params[:task][:project_id].nil?
      @task = current_user.tasks.create(task_params)
    else
      @project = Project.find(params[:task][:project_id])
      @task = @project.tasks.create(task_params)
    end
    respond_to do |format|
      format.html {redirect_to request.referrer}
      format.js
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    if params[:task][:project_id]
      @task = Project.find(params[:task][:project_id]).tasks.find(params[:id])
      @task.update(task_params)
    else
      @task = current_user.tasks.find(params[:id])
      @task.update(task_params)
    end
    respond_to do |format|
      format.html {redirect_to request.referrer}
      format.js
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    current_user.tasks.delete(@task)
    @task.destroy
  end

  def task_params
    params.require(:task).permit(:title, :description, :priority, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    resource.errors.full_messages.map { |msg| content_tag(:l, msg) }
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="loader-wrapper">
  <div id="loader"></div>

  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>

</div>
<!--Hero-->
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <h1 class="text_h center header cd-headline letters type">
      Welcome to ManEgment
      <p>
      <% if !user_signed_in? %>
        <%= link_to "Log in", new_session_path(User), class: "waves-effect waves-light btn-large hoverable" %>
        <%= link_to "Sign up", new_registration_path(User), class: "waves-effect waves-light btn-large hoverable" %>
      <% end %>
      </p>
    </h1>
  </div>
</div>

<!--Intro and service-->
<div id="intro" class="section scrollspy">
  <div class="container">
    <div class="row">
      <div  class="col s12">
        <h2 class="center header text_h2"> A site for managing your daily <span class="span_h2"> tasks  </span> and <span class="span_h2"> projects.</span> </h2><br /><br /><br />
      </div>

      <div  class="col s12 m4 l4">
        <div class="center promo promo-example">
          <i class="material-icons">flash_on</i>
          <h5 class="promo-caption">Speeds Up Development</h5>
          <p class="light center">Keep track of project progress and task completion. Never loose track of your important projects again!</p>
        </div>
      </div>
      <div class="col s12 m4 l4">
        <div class="center promo promo-example">
          <i class="material-icons">group</i>
          <h5 class="promo-caption">User Experience Focused</h5>
          <p class="light center">Easy to navigate and use. Simple user interface to make keeping track of things a breeze.</p>
        </div>
      </div>
      <div class="col s12 m4 l4">
        <div class="center promo promo-example">
          <i class="material-icons">desktop_windows</i>
          <h5 class="promo-caption">Fully Responsive</h5>
          <p class="light center">Fully mobile responsive site so you can use it on the go.</p>
        </div>
      </div>
    </div>
  </div>
</div>