config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :user_projects, only: [:create, :update, :destroy]
  resources :user_groups, only: [:create, :update, :destroy]

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      confirmation: 'users/confirmations',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }, path: 'users', path_names: {
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'sign_up'
  }
  resources :users, only: [:index, :show]
  resources :tasks
  resources :projects
  resources :groups
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users,-> {where(user_groups: {accepted: true})}, through: :user_groups, source: :user
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :projects
end

app/models/group_task.rb
class GroupTask < ApplicationRecord
  belongs_to :task
  belongs_to :group
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: "User"
  belongs_to :notifiable, polymorphic: true
  after_commit -> {NotificationRelayJob.perform_later(self)}
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_tasks
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :tasks, through: :project_tasks
  has_many :completed_tasks, -> {where(tasks: {completed: true})}, through: :project_tasks, source: :task
  belongs_to :group
  before_destroy :destroy_user_projects

  def progress
    ((completed_tasks.count.to_f/tasks.count.to_f)*100)
  end

  def destroy_user_projects
    self.user_projects.delete_all
    self.tasks.delete_all
  end
end

app/models/project_task.rb
class ProjectTask < ApplicationRecord
  belongs_to :task
  belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_tasks
  has_many :tasks, through: :user_tasks
  has_many :user_projects
  has_many :projects, through: :user_projects
  has_many :user_groups
  has_many :owned_groups, class_name: "Group", foreign_key: "owner_id"
  has_many :recieved_group_invites, class_name: "UserGroup", foreign_key: "group_id"

  has_many :active_groups, -> {where(user_groups: {accepted: true})}, through: :user_groups, source: :group
  has_many :received_groups, -> {where(user_groups: {accepted: true})}, through: :recieved_group_invites, source: :user
  has_many :pending_groups, -> {where(user_groups: {accepted: false})}, through: :user_groups, source: :group
  has_many :requested_groups, -> {where(user_groups: {accepted: false})}, through: :recieved_group_invites, source: :user


  has_many :friendships
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"

  has_many :active_friends, -> {where(friendships: {accepted: true})}, through: :friendships, source: :friend
  has_many :received_friends, -> {where(friendships: {accepted: true})}, through: :received_friendships, source: :user
  has_many :pending_friends, -> {where(friendships: {accepted: false})}, through: :friendships, source: :friend
  has_many :requested_friends, -> {where(friendships: {accepted: false})}, through: :received_friendships, source: :user

  has_many :notifications, foreign_key: :recipient_id


  def full_name
    first_name + ' ' + last_name
  end

  def owner?(group)
    owned_groups.include?(group)
  end

  def friends
    active_friends | received_friends
  end

  def friends_pending
    pending_friends | requested_friends
  end

  def friends_with?(user)
    friends.include?(user)
  end

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end

  def groups
    active_groups | received_groups
  end

  def groups_pending
    pending_groups | requested_groups
  end

  def in_group?(group)
    groups.include?(group)
  end

  def remove_group(group)
    current_user.groups.destroy(group)
  end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def check_email
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
  end

  def create
    @group = Group.find(params[:project][:group_id])
    @project = @group.projects.create(project_params)
  end

  def update
  end

  def edit
    @project = Project.find(params[:id])
    @users = User.all
  end

  def destroy
    @project = Project.find(params[:id])
    @project.group.projects.destroy(params[:id])
    @project.destroy
    redirect_to group_path(@project.group)
  end

  def project_params
    params.require(:project).permit(:title, :description, :group_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def show
  end

  def new
    @task = Task.new
    @project = Project.new
  end

  def create
    params[:task][:completed] = false
    if params[:task][:project_id].nil?
      @task = current_user.tasks.create(task_params)
    else
      @project = Project.find(params[:task][:project_id])
      @task = @project.tasks.create(task_params)
    end
    respond_to do |format|
      format.html {redirect_to request.referrer}
      format.js
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    if params[:task][:project_id]
      @task = Project.find(params[:task][:project_id]).tasks.find(params[:id])
      @task.update(task_params)
    else
      @task = current_user.tasks.find(params[:id])
      @task.update(task_params)
    end
    respond_to do |format|
      format.html {redirect_to request.referrer}
      format.js
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    current_user.tasks.delete(@task)
    @task.destroy
  end

  def task_params
    params.require(:task).permit(:title, :description, :priority, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    resource.errors.full_messages.map { |msg| content_tag(:l, msg) }
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_project.html.erb
<li id="Project<%= project.id %>">
  <div class="collapsible-header"><%= link_to project.title, project_path(project) %>
    <a href="<%= edit_project_path(project) %>" class="right"><i class="material-icons">settings</i></a>
    <div class="progress">
      <div class="determinate" style="width: <%= project.progress %>%"></div>
    </div>
  </div>
  <div class="collapsible-body">
    <ul class="collection" id="task-list">
        <%= render project.tasks %>
    </ul>
  </div>
</li>

app/views/projects/create.html.erb
<h1>Project#create</h1>
<p>Find me in app/views/project/create.html.erb</p>

app/views/projects/create.js.erb
$('#project-list').append("<%= j render @project %>");

app/views/projects/destroy.html.erb
<h1>Project#destroy</h1>
<p>Find me in app/views/project/destroy.html.erb</p>

app/views/projects/edit.html.erb
<div class="container">
  <div class="card">
    <div class="card-content">
      <div class="card-title"><%= @project.title %>
        <div class="progress">
          <div class="determinate" style="width: <%= @project.progress %>%"></div>
        </div>
      </div>
      <%= form_with model: @project, method: :patch do |f| %>
          <%= f.label :title %>
          <%= f.text_field :title %>
          <%= f.label :description %>
          <%= f.text_area :description, class: "materialize-textarea" %>
          <%= f.submit "Update Project", class: "btn" %>
      <% end %>
      <%= link_to "Delete Project", project_path(@project), method: :delete, class: "btn", remote: true %>
      <div class="card-title">Users</div>
      <ul class="collection">
        <% @project.users.each do |u| %>
            <li class="collection-item"><%= u.username %></li>
        <% end %>
      </ul>
      <div class="card-title">Tasks</div>
      <ul class="collection">
        <% @project.tasks.each do |t| %>
            <li id="Task<%= t.id %>" class="collection-item">
              <a href="<%= edit_task_path(t) %>" class="secondary-content"><i class="material-icons">mode_edit</i></a>
              <%= link_to "Delete".html_safe, task_path(t), class: "secondary-content", data: {confirm: "Are you sure?"}, method: :delete, remote: true %>
              <%= form_with(model: t, id: "complete#{t.id}", remote: true) do |f| %>
                  <%= f.hidden_field :project_id, value: @project.id %>
                  <%= f.check_box(:completed, {:class => 'fillied-in', id: "check_box#{t.id}", onchange: "$('#complete#{t.id}').submit()"}, "true", "false") %>
                  <label for="check_box<%= t.id %>"><%= link_to(t.title, tasks_path(t)) %></label>
                  <%= f.submit '', {:style => "display: none;"} %>
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="fixed-action-btn click-to-toggle">
  <a class="btn-floating btn-large red">
    <i class="material-icons">add</i>
  </a>
  <ul>
    <li>
      <a href="#add_user" class="btn-floating red tooltipped" data-position="left" data-tooltip="Add User"><i class="material-icons">perm_identity</i></a>
    </li>
    <li>
      <a href="#new_task" class="btn-floating red tooltipped" data-position="left" data-tooltip="Add Task"><i class="fa fa-tasks"></i></a>
    </li>
  </ul>
</div>
<%= form_with(model: @project.tasks.new) do |f| %>
    <div class="modal bottom-sheet" id="new_task">
      <div class="modal-content">
        <%= f.hidden_field :project_id, value: @project.id %>
        <h4>Create Task</h4>
        <div class="input-field">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>
        <div class="input-field">
          <%= f.label :description %>
          <%= f.text_area :description, class: "materialize-textarea" %>
        </div>
        <div class="input-field">
          <%= f.submit 'Create Task', class: "btn" %>
        </div>
      </div>
    </div>
<% end %>
<div class="modal bottom-sheet" id="add_user">
  <div class="modal-content">
    <%= form_with(model: UserProject.create, remote: true) do |f| %>
        <%= f.hidden_field :project_id, value: @project.id %>
        <div class="input-field">
          <%= f.select :users, @project.group.users.collect {|u| [u.username, u.id]}, {include_blank: false}, id: "add_users", multiple: true, style: "width: 100%" %>
        </div>
        <%= f.submit "Add Users", class: "btn" %>
    <% end %>
    <script>
        function formatExample(user) {
            var originalOption = $(user.element);
            return "   " + user.text;
        }

        $('select#add_users').select2({
            placeholder: "Add a User",
            allowClear: true,
            formatResult: formatExample,
            formatSelection: formatExample,
            escapeMarkup: function (m) {
                return m;
            }
        });
    </script>
  </div>
</div>
<script>
    $('.modal').modal({
            dismissible: true, // Modal can be dismissed by clicking outside of the modal
            opacity: .5, // Opacity of modal background
            inDuration: 300, // Transition in duration
            outDuration: 200, // Transition out duration
            startingTop: '4%', // Starting top style attribute
            endingTop: '10%' // Ending top style attribute
        }
    );
</script>

app/views/projects/index.html.erb
<h1>Project#index</h1>
<p>Find me in app/views/project/index.html.erb</p>

app/views/projects/new.html.erb
<div class="container">
  <div class="card">
    <div class="card-content">
      <div class="card-title">Create Project</div>
      <div class="card-block">
        <%= form_with(model: @project) do |f| %>
            <div class="input-field">
              <%= f.label :title %>
              <%= f.text_field :title %>
            </div>
            <div class="input-field">
              <%= f.label :description %>
              <%= f.text_area :description, class: "materialize-textarea" %>
            </div>
            <div class="input-field">
              <%= f.label :priority %>
              <%= f.number_field :priority, min: 0, max: 5 %>
            </div>
            <div class="input-field">
              <%= f.submit 'Create Project', class: "btn" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-content">
      <div class="card-title"><%= @project.title %>
        <div class="progress">
          <div class="determinate" style="width: <%= @project.progress %>%"></div>
        </div>
      </div>
      <div class="card-title">Users</div>
      <ul class="collection">
        <% @project.users.each do |u| %>
            <li class="collection-item"><%= u.username %></li>
        <% end %>
      </ul>
      <div class="card-title">Tasks</div>
      <ul class="collection">
        <% @project.tasks.each do |t| %>
            <li id="Task<%= t.id %>" class="collection-item">
              <%= check_box("completed", t.id, {checked: t.completed}) %>
              <label for="check_box<%= t.id %>"><%= link_to(t.title, tasks_path(t)) %></label>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/projects/update.html.erb
<h1>Project#update</h1>
<p>Find me in app/views/project/update.html.erb</p>