config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :user_projects, only: [:create, :update, :destroy]
  resources :user_groups, only: [:create, :update, :destroy]

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      confirmation: 'users/confirmations',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }, path: 'users', path_names: {
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'sign_up'
  }
  resources :users, only: [:index, :show]
  resources :tasks
  resources :projects
  resources :groups
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users,-> {where(user_groups: {accepted: true})}, through: :user_groups, source: :user
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :projects
end

app/models/group_task.rb
class GroupTask < ApplicationRecord
  belongs_to :task
  belongs_to :group
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: "User"
  belongs_to :notifiable, polymorphic: true
  after_commit -> {NotificationRelayJob.perform_later(self)}
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_tasks
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :tasks, through: :project_tasks
  has_many :completed_tasks, -> {where(tasks: {completed: true})}, through: :project_tasks, source: :task
  belongs_to :group
  before_destroy :destroy_user_projects

  def progress
    ((completed_tasks.count.to_f/tasks.count.to_f)*100)
  end

  def destroy_user_projects
    self.user_projects.delete_all
    self.tasks.delete_all
  end
end

app/models/project_task.rb
class ProjectTask < ApplicationRecord
  belongs_to :task
  belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_tasks
  has_many :tasks, through: :user_tasks
  has_many :user_projects
  has_many :projects, through: :user_projects
  has_many :user_groups
  has_many :owned_groups, class_name: "Group", foreign_key: "owner_id"
  has_many :recieved_group_invites, class_name: "UserGroup", foreign_key: "group_id"

  has_many :active_groups, -> {where(user_groups: {accepted: true})}, through: :user_groups, source: :group
  has_many :received_groups, -> {where(user_groups: {accepted: true})}, through: :recieved_group_invites, source: :user
  has_many :pending_groups, -> {where(user_groups: {accepted: false})}, through: :user_groups, source: :group
  has_many :requested_groups, -> {where(user_groups: {accepted: false})}, through: :recieved_group_invites, source: :user


  has_many :friendships
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"

  has_many :active_friends, -> {where(friendships: {accepted: true})}, through: :friendships, source: :friend
  has_many :received_friends, -> {where(friendships: {accepted: true})}, through: :received_friendships, source: :user
  has_many :pending_friends, -> {where(friendships: {accepted: false})}, through: :friendships, source: :friend
  has_many :requested_friends, -> {where(friendships: {accepted: false})}, through: :received_friendships, source: :user

  has_many :notifications, foreign_key: :recipient_id


  def full_name
    first_name + ' ' + last_name
  end

  def owner?(group)
    owned_groups.include?(group)
  end

  def friends
    active_friends | received_friends
  end

  def friends_pending
    pending_friends | requested_friends
  end

  def friends_with?(user)
    friends.include?(user)
  end

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end

  def groups
    active_groups | received_groups
  end

  def groups_pending
    pending_groups | requested_groups
  end

  def in_group?(group)
    groups.include?(group)
  end

  def remove_group(group)
    current_user.groups.destroy(group)
  end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    resource.errors.full_messages.map { |msg| content_tag(:l, msg) }
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= javascript_tag "Materialize.toast('#{message}', 4000)" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manegment</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
  <!-- Compiled and minified CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="col s12 m6">
<%= render 'layouts/flash' %>
<% if user_signed_in? %>
    <ul id="dropdown" class="dropdown-content">
      <li><a href="<%= users_path(current_user) %>">Dashboard</a></li>
      <li><a href="<%= user_path(current_user) %>">Profile</a></li>
      <li><a href="<%= edit_user_registration_path %>">Settings</a></li>
      <li class="divider"></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    </ul>
    <ul id="dropdown-mobile" class="dropdown-content">
      <li><a href="<%= users_path(current_user) %>">Dashboard</a></li>
      <li><a href="<%= user_path(current_user) %>">Profile</a></li>
      <li><a href="<%= edit_user_registration_path %>">Settings</a></li>
      <li class="divider"></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    </ul>
<% end %>
<nav class="red darken-4">
  <div class="nav-wrapper">
    <a href="<%= root_path %>" class="brand-logo">ManEgment</a>
    <a data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
          <li><a href="<%= new_group_path %>">Create Group</a></li>
          <li>
            <a class="dropdown-button" data-activates="dropdown-mobile" data-beloworigin="true"><%= current_user.username %>
              <i class="material-icons right">arrow_drop_down</i></a></li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile">
      <li><a href="<%= new_group_path %>">Create Group</a></li>
      <% if user_signed_in? %>
          <li>
            <a class="dropdown-button-mobile" data-activates="dropdown" data-beloworigin="true"><%= current_user.username %>
              <i class="material-icons right">arrow_drop_down</i></a></li>
      <% end %>
    </ul>
  </div>
</nav>
<%= yield %>
</body>
</html>